apiVersion: v1
kind: Service
metadata:
  name: seattype-api
spec:
  selector:
    app: seattype-api
  type: ClusterIP
  ports:
    - name: seattype-api
      protocol: TCP
      port: 8000
      targetPort: 8000
