apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: statistic-api-ingress
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/api/statistics`)
      middlewares:
        - name: strip-api
      services:
        - name: statistic-api
          port: 8000
