apiVersion: v1
kind: Service
metadata:
  name: statistic-api
spec:
  selector:
    app: statistic-api
  type: ClusterIP
  ports:
    - name: statistic-api
      protocol: TCP
      port: 8000
      targetPort: 8000
