apiVersion: v1
kind: Service
metadata:
  name: ticket-api
spec:
  selector:
    app: ticket-api
  type: ClusterIP
  ports:
    - name: ticket-api
      protocol: TCP
      port: 8000
      targetPort: 8000
