apiVersion: v1
kind: Service
metadata:
  name: payment-api
spec:
  selector:
    app: payment-api
  type: ClusterIP
  ports:
    - name: payment-api
      protocol: TCP
      port: 8000
      targetPort: 8000
