apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-api
  labels:
    app: cinema-api
spec:
  selector:
    matchLabels:
      app: cinema-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cinema-api
    spec:
      containers:
        - name: cinema-api-ctn
          image: nguyen040904/cinema-api:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: cinema-api-port
          volumeMounts:
            - name: env
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env
          configMap:
            name: global-env
      restartPolicy: Always
