apiVersion: v1
kind: Service
metadata:
  name: cinema-api
spec:
  selector:
    app: cinema-api
  type: ClusterIP
  ports:
    - name: cinema-api
      protocol: TCP
      port: 8000
      targetPort: 8000
