apiVersion: v1
kind: Service
metadata:
  name: movie-api
spec:
  selector:
    app: movie-api
  type: ClusterIP
  ports:
    - name: movie-api
      protocol: TCP
      port: 8000
      targetPort: 8000
