apiVersion: v1
kind: Service
metadata:
  name: search-api
spec:
  selector:
    app: search-api
  type: ClusterIP
  ports:
    - name: search-api
      protocol: TCP
      port: 8000
      targetPort: 8000
